// redux-react/App.jsx
import React from 'react';
import Button from './Button';
import Output from './Output';
import { increment, decrement, reset } from './actions';
import { isPrime } from './selectors';

import { connect } from 'react-redux';

const App = ({ value, isPrime, decrement, increment, reset }) => {
    return (
        <main>
            <Output label="Counter" value={value} />
            <Output label="Counter * 2" value={value * 2} />
            <Output label="Is prime number?" value={String(isPrime)} />
            <Button onClick={increment}>Increment (+)</Button>
            <Button onClick={decrement}>Decrement (+)</Button>
            <Button onClick={reset}>Reset</Button>
        </main>
    );
};

const mapStateToProps = state => ({
    value: state.counter,
    isPrime: isPrime(state.counter)
});

const mapDispatchToProps = dispatch => ({
    increment: () => dispatch(increment(1)),
    decrement: () => dispatch(decrement(1)),
    reset: () => dispatch(reset())
});

export default connect(mapStateToProps, mapDispatchToProps)(App);

// angular-ngrx/app.component.ts
import { Component } from "@angular/core";
import { Store, select } from "@ngrx/store";
import { Observable } from "rxjs";

import { increment, decrement, reset } from "./actions";
import { getCount, getDoubleCount, getIsPrime } from "./selectors";

@Component({
    selector: "my-app",
    templateUrl: "./app.component.html"
})
export class AppComponent {
    counter$: Observable<number>;
    doubleCounter$: Observable<number>;
    isPrime$: Observable<boolean>;

    constructor(private store: Store<{ count: number }>) {
        this.counter$ = store.pipe(select(getCount));
        this.doubleCounter$ = store.pipe(select(getDoubleCount));
        this.isPrime$ = store.pipe(select(getIsPrime));
    }

    onIncrement() {
        this.store.dispatch(increment({ number: 1 }));
    }

    onDecrement() {
        this.store.dispatch(decrement({ number: 1 }));
    }

    onReset() {
        this.store.dispatch(reset());
    }
}

<div>
	<app-output [value]="counter$ | async" label="Counter"></app-output>
	<app-output [value]="doubleCounter$ | async" label="Counter * 2"></app-output>
	<app-output [value]="isPrime$ | async" label="Is prime number?"></app-output>
	<app-button (click)="onIncrement()">Increment (+)</app-button>
	<app-button (click)="onDecrement()">Decrement (-)</app-button>
	<app-button (click)="onReset()">Reset</app-button>
</div>
